### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by pat-lego** [AES-Outreach/Outreach-Wiki#126]

**Comment by pat-lego** [comment]
Document for requirements is here: https://drive.google.com/open?id=1mN9szdjs-pXVd3GkaIZKYSe6YU4xGRBJScUU0sJ5LJY

**Comment by callmekungfu** [comment]
I am not authorized to this link.
Is it for the document titled: "Documentation TODO's"

**Comment by Digized** [comment]
## Endpoint
### Request: 
Headers: outreachLang, outreachAppData, outreachAuthorization
queryString: start=1990-06-01&end=1990-06-08

### Response
```json
{
    "data": [
        {
            "start_date": "2019-12-06",
            "end_date": "2019-12-06",
            "start_time": "12:00",
            "end_time": "16:00",
            "capacity": 200,
            "count": 100,
            "term_id": 1,
            "term_label_code":"fall",
            "program_code": "teentech-2",
            "region_code": "campus",
            "language_full": "English",
            "idea_title": "5 Senses",
            "instructors": [
                {
                    "contact_id": 1,
                    "first_name": "Test",
                    "last_user": "User"
                }
            ],
            "vehicles": [
                {
                    "vehicle_id": 1,
                    "vehicle_label": "MakerMobile"
                }
            ]
        }
    ]
}
```

**Comment by callmekungfu** [comment]
## Front End Proof of Concept
I worked on a front end proof of concept for the weekly calendar [https://codepen.io/redmond_fun/pen/ROXLae](https://codepen.io/redmond_fun/pen/ROXLae)

## Screenshot
Here is a screenshot of the result:
![download (1)](https://user-images.githubusercontent.com/11084692/57139655-d7318180-6d83-11e9-83f1-80521795e3df.png)

## Some Code
### HTML
```html
<div class="calendar">
  <!--  Header  -->
  <div class="inner info">Select goes here</div>
  <div class="inner info">December 1st</div>
  <div class="inner info"><span>December 2nd</span></div>
  <div class="inner info"><span>December 3rd</span></div>
  <div class="inner info"><span>December 4th</span></div>
  <div class="inner info"><span>December 5th</span></div>
  <div class="inner info"><span>December 6th</span></div>
  <div class="inner info"><span>December 7th</span></div>
  <!--  /Header  -->
  
  <!--  Row 1  -->
  <div class="inner info">Van 1</div>
  <div class="inner">
    <div class="event">
      <h4>Campus</h4>
      <p>8:00 - 16:00</p>
    </div>
  </div>
  <div class="inner"></div>
  <div class="inner"></div>
  <div class="inner"></div>
  <div class="inner">
    <div class="event">
      <h4>Campus</h4>
      <p>8:00 - 16:00</p>
    </div>
    <div class="event">
      <h4>Campus</h4>
      <p>8:00 - 16:00</p>
    </div>
  </div>
  <div class="inner"></div>
  <div class="inner"></div>
  <!--  /Row 1  -->

  <!--  More Rows  After This -->
</div>
```

### CSS
```css
@import url('https://fonts.googleapis.com/css?family=Roboto');

* {
  box-sizing: border-box;
}

body {
  font-family: 'Roboto', sans-serif;
}

.calendar {
  width: 100%;
  display: grid;
  grid-template-columns: repeat(8, minmax(120px, 1fr));
  grid-template-rows: 60px;
  grid-auto-rows: minmax(max-content, 120px);
}

.inner {
  padding: 20px;
  border: solid 1px #000;
  text-align: center;
}

.info {
  background: #D3D3D3;
}

.event {
  background: #50c878;
  border: 2px solid #0c8c37;
  cursor: pointer;
  padding: 25px 0;
  margin-bottom: 10px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
  transition: all 0.25s ease-in-out;
}
.event:hover {
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
}
```
